version: '3.7'
services: 
    frontend: 
    image: frontend-shop
    ports:
        - 4000:3000
    depends_on: 
        - backend
    backend:
        image: backend
        ports:
            -8200:80
    mysql:
        image: mysql:5.7
        environment: 
            MYSQL_ROOT_PASSWORD: 
            MYSQL_DATABASE: ecommerce
            MYSQL_USER: root
            MYSQL_PASSWORD:

